/*********************************************************************************
Class Name      : Credomatic_FAOpenState
Description     : This class implements the Financial Account State pattern class and handles the functionality
				  related to the Open status on Financial Account record
Created By      : Sebastian Torres
Created Date    : 2021-05-05
Modification Log:
---------------------------------------------------------------------------------- 
Developer                   Date                   Description
----------------------------------------------------------------------------------
Sebastian                 2021-05-05              Initial version
*********************************************************************************/
public class Credomatic_FAOpenState implements Credomatic_FinancialAccountState {
    
    public void rollupBalance(FinServ__FinancialAccount__c financialAccount)
    {
        
    }
    
    public void validateAccountNumber(FinServ__FinancialAccount__c financialAccount)
    {
        
    }
    public void closeAccount(FinServ__FinancialAccount__c financialAccount)
    {
        
    }
    public void validateShippingAddress(FinServ__FinancialAccount__c financialAccount)
    {
        
    }

}